# vim keybindings
setw -g mode-keys vi

# select enable
set -g mouse on

set -g default-command zsh

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Ajust terminal color issue - uncomment if needed
#set-option -g default-terminal "tmux-256color"
#set-option -sa terminal-overrides ",xterm-256color:RGB"

set -g status-bg default
set -g status-fg default
set -g pane-border-style fg=default
set -g pane-active-border-style fg=default

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
